# Generated by Django 3.0.3 on 2020-05-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
    ]
