# Generated by Django 3.0.6 on 2020-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200605_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='destination',
            field=models.CharField(max_length=20),
        ),
    ]
