# Generated by Django 3.0.7 on 2020-06-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200605_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattributes',
            name='img',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
