language: python
python:
  - '3.6'

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="traveler.settings"

services:
  - postgresql

script:
  - coverage run manage.py test